### ISSUE TITLE
How is an ongoing updater route arranged?

### ISSUE THREAD

**Issue by n14s** [eclipse-basyx/basyx-databridge#2]
The examples are all structured similarly.
The route is set up, the updater is started, data is transmitted, and finally the updater is stopped again.

`updater.startComponent();`
`System.out.println("UPDATER STARTED");`
`System.out.println("PUBLISH EVENT");`
`publishNewDatapoint(); ` 
`publishNewDatapoint2();`  
`System.out.println("EVENT PUBLISHED"); `
`checkIfPropertyIsUpdated();  `
`updater.stopComponent();`

I'm looking for a way, to keep the updater going for a indefinite amount of time, until one actively terminates the process.

When removing the "updater.stopComponent()" command, the program terminates nevertheless.
The only way I managed to have the desired result of an ongoing updater route, was by integrating a "Thread.sleep()" command with a large time argument.

There must be a better way, right?

**Comment by FrankSchnicke** [comment]
This is now fixed here: https://github.com/eclipse-basyx/basyx-databridge/tree/main/basyx.components.databridge

Additionally, you can use the released image on DockerHub: 
https://hub.docker.com/r/eclipsebasyx/databridge
