### ISSUE TITLE
Two Issues running kafka-jsonata-aas example

### ISSUE THREAD

**Issue by Jusainj** [eclipse-basyx/basyx-databridge#228]
Hi,

I am having trouble running the `example kafka-jsonata-aas` as described in the following two steps:

1. There might be a problem with the configuration of `kafkaconsumer.json`.
Using the `seekTo: latest` parameter, which is specified in the [example configuration](https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples/databridge.examples.kafka-jsonata-aas/src/main/resources) and the [documentation](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_DataBridge_/_Features_/_Protocol_Integration_/_Kafka), forces the Databridge component to stop. One reason for this could be that only two values `BEGINNING` and `END` specified in the SeekPolicy [Camel Kafka Component](https://camel.apache.org/components/3.20.x/kafka-component.html#_query_parameters) may be used.

 2. To avoid a forced stop of the databridge component, I used a valid value for the "seekTo" parameter. This allows a run without harmful errors from the Databridge component. The databridge sets up, connects to the running Kafka broker, and subscribes to a defined topic `first-topic` (according to the log messages). After a successful connection between the Kafka consumer and the broker, the databridge directly disconnects from the server and continuously returns the following log messages:
```
 [Camel (camel-1) thread #1 - KafkaConsumer[first-topic]] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-basyx-updater-1, groupId=basyx-updater] Node -1 disconnected.
 
 [Camel (camel-1) thread #1 - KafkaConsumer[first-topic]] WARN org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-basyx-updater-1, groupId=basyx-updater] Connection to node -1 (/127.0.0.1:9092) could not be established. Broker may not be available.
``` 

Is this a known issue or do you have a workaround to successfully subscribe to Kafka events using the Databridge component?

**Comment by FrankSchnicke** [comment]
Thanks for pointing out this error in our examples. We will take a look at the issue and come back to you soon.

**Comment by FrankSchnicke** [comment]
The issue should be fixed with the latest PR. Feel free to take a look and close this ticket if the issue is also fixed on your end.

**Comment by Jusainj** [comment]
With the latest PR the issue disappeared on my side as well and I can now receive Kafka messages with the Databridge component. 
Thanks for the fix!
