### ISSUE TITLE
OPC UA - Missing Security settings

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-databridge#241]
Hi,

in my project I need to transfer data from an OPC UA server to the AAS Server via the AAS Databridge. The problem is that the [OpcuaConsumerConfiguration](https://github.com/eclipse-basyx/basyx-databridge/blob/main/databridge.camel-opcua/src/main/java/org/eclipse/digitaltwin/basyx/databridge/opcua/configuration/OpcuaConsumerConfiguration.java) only handles connection with `SecurityPolicies` None but our OPC UA server requires a the Policy `Basic256Sha256`.

So my question is if I just misunderstood the configuration and it is possible after all or this is really missing. If this is missing, would it be possible to add this?

KR,
BlackRose01

**Comment by FrankSchnicke** [comment]
This is currently missing. However, feel free to raise a pull request adding this feature. Since we're directly mapping the JSON configuration files to the java classes, adding the needed fields to the OpcuaConsumerConfiguration and changing the getConnectionURI method is sufficient. 

Would this be an idea?

**Comment by BlackRose01** [comment]
This is ok. Are there any requirements to create a pull request like signing the Eclipse Contributor Agreement (ECA) or a name convention for the branch?

**Comment by FrankSchnicke** [comment]
Yes, you have to sign the ECA. Just raise a PR on main, there's no need for a specific branch name

**Comment by BlackRose01** [comment]
I created the Pull Request with the necessary changes.

**Comment by BlackRose01** [comment]
Is there any schedule when the new Docker image will be published on Docker Hub?

**Comment by FrankSchnicke** [comment]
In the next release, we would like to also include https://github.com/eclipse-basyx/basyx-databridge/pull/234 which will be merged most likely this week.

However, I can gladly push a SNAPSHOT image to DockerHub if you need an image on DockerHub that includes your PR at an earlier time.

**Comment by BlackRose01** [comment]
That would be great. So I can test the implementation and push our project forward.

**Comment by FrankSchnicke** [comment]
I pushed the snapshot version to [DockerHub](https://hub.docker.com/layers/eclipsebasyx/databridge/1.0.0-SNAPSHOT/images/sha256-e9dcef9670960a0f04d67d0aa4f28dc1efb27d78cb26dad162ead7455027b19f?context=explore).
