### ISSUE TITLE
How the Docker image is created?

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-databridge#252]
Hello,

Unfortunately I had to realize that with our project partner the implemented fix for OPC UA helped but was not the solution. Apparently Siemens PLCs have a very special way how to connect to the server with an OPC UA client. It is not possible for me to virtualize the configuration of this server.

Hence my question if you could push the Dockerfile into the repo as well? Then we could build Docker image for testing purposes and at the same time even create a flow in that repo that does an automated rollout of the image to Docker Hub (based on a tag or so).

KR,
BlackRose01

**Comment by FrankSchnicke** [comment]
Hi,

the DockerFile is here: https://github.com/eclipse-basyx/basyx-databridge/blob/main/databridge.component/Dockerfile

Additionally, you can build the Image by using _mvn install -Pdocker_ (optionally with _-DskipTests_ to skip tests) on the root of the project.
