### ISSUE TITLE
[Suggestion] Validation of JSON configuration files againts JSON Schema file 

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-databridge#263]
Hi,

I have a suggestion to standardize the validation of the JSON configuration, extend it slightly and make it more readable for external developers. This is especially helpful if you want to change certain options or have to rebuild the whole configuration file.

Therefore, I would recommend the use of [JSON Schema](https://json-schema.org). This is a specification for describing the structure of JSON files. Also provided are libraries [1] for it that provide validation of the schema with a JSON string/object.

Since I need to create some AAS Databridges in my current project Fed-X-Pro, I created a tool for me where I can create just these configurations for the AAS. I have the form for this created based on the schema and at the same time validate the data entered against it.

The advantages of this would be the following:
* Eclipse Basyx would have an easy way to validate without custom deserializers or rules.
* Changes of the schema file has no influence on the source code
* Rules for creating configuration files are centralized in the repository and can be easily maintained
* Users can immediately see what the configuration files must look like and what individual constraints are
* External developers can reference these files and, like me for example, build tools on top of them

[1] Example for library: [Vertx](https://vertx.io/docs/vertx-json-schema/java/)

KR,
BlackRose01

---

## JSON Schema for `opcuaconsumer.json`
```json
{
    "$id": "https://example.com/person.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "opcuaconsumer.json",
    "type": "object",
    "required": [
        "uniqueId",
        "pathToService",
        "nodeInformation"
    ],
    "properties": {
        "uniqueId": {
            "title": "Unique ID",
            "type": "string",
            "description": "Unique ID to match options",
            "pattern": "^[a-z0-9-]+$"
        },
        "serverUrl": {
            "title": "Hostname or IP",
            "type": "string",
            "description": "IP or Hostname of the OPC UA Server",
            "default": "127.0.0.1",
            "pattern": "^([a-z0-9-_\\.]+\\.[a-z]{1,3}|[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})$"
        },
        "serverPort": {
            "title": "Port",
            "description": "Port of the OPC UA Server",
            "type": "integer",
            "minimum": 0,
            "maximum": 65535,
            "default": "4048"
        },
        "pathToService": {
            "title": "Path to Service",
            "type": "string",
            "description": "URI of the Service in the OPC UA Server",
            "pattern": "[a-z/]+"
        },
        "nodeInformation": {
            "title": "OPC UA Node ID",
            "type": "string",
            "description": "Path to a variable node in the OPC UA Server"
        },
        "username": {
            "title": "Username",
            "type": "string",
            "description": "Username to authenticate to the OPC UA Server"
        },
        "password": {
            "title": "Password",
            "type": "string",
            "description": "Password to authenticate to the OPC UA Server"
        },
        "parameters": {
            "title": "Parameters",
            "type": "object",
            "properties": {
                "requestedPublishingInterval": {
                    "type": "integer",
                    "description": "Interval to request the value of the variable",
                    "minimum": 500,
                    "default": "500"
                },
                "clientId": {
                    "type": "string",
                    "description": "A virtual client id to force the creation of a new connection instance"
                },
                "dataChangeFilterDeadbandType": {
                    "type": "integer",
                    "description": "Deadband type for MonitorFilterType DataChangeFilter"
                },
                "dataChangeFilterDeadbandValue": {
                    "type": "number",
                    "description": "Deadband value for MonitorFilterType DataChangeFilter"
                },
                "allowedSecurityPolicies": {
                    "enum": [
                        "None",
                        "Basic128Rsa15",
                        "Basic256",
                        "Basic256Sha256",
                        "Aes128_Sha256_RsaOaep",
                        "Aes256_Sha256_RsaPss"
                    ],
                    "default": "None",
                    "description": "A set of allowed security policy URIs. Default is to accept all and use the highest"
                },
                "keyAlias": {
                    "type": "string",
                    "description": "The name of the key in the keystore file"
                },
                "keyPassword": {
                    "type": "string",
                    "description": "The key password"
                },
                "keyStorePassword": {
                    "type": "string",
                    "description": "The keystore password"
                },
                "keyStoreType": {
                    "type": "string",
                    "description": "The key store type"
                },
                "keyStoreUrl": {
                    "type": "string",
                    "description": "The URL where the key should be loaded from"
                },
                "sessionName": {
                    "type": "string",
                    "description": "Session name",
                    "pattern": "[a-z0-9-]*"
                },
                "sessionTimeout": {
                    "type": "integer",
                    "description": "Session timeout in milliseconds",
                    "minimum": 0
                }
            }
        }
    }
}
```

**Comment by FrankSchnicke** [comment]
This is an interesting idea. Would you be willing to contribute your created JSON schemas?

**Comment by BlackRose01** [comment]
Actually I'm not sure if I have all consumers/transformers transfered to JSON-Schema but here are my current files. Maybe you also have to adjust some points to meet your requirements but basically they should work.

## Consumers
[honoconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857082/honoconsumer.schema.json)
[httpconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857083/httpconsumer.schema.json)
[kafkaconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857084/kafkaconsumer.schema.json)
[mqttconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857085/mqttconsumer.schema.json)
[opcuaconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857086/opcuaconsumer.schema.json)
[plc4xconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857087/plc4xconsumer.schema.json)
[activemqconsumer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857088/activemqconsumer.schema.json)

## Transformers
[jsonatatransformer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857091/jsonatatransformer.schema.json)
[jsonjacksontransformer.schema.json](https://github.com/eclipse-basyx/basyx-databridge/files/12857092/jsonjacksontransformer.schema.json)

KR,
BlackRose01
