### ISSUE TITLE
MILO client not working with localhost OPCUA server. Using OPC2AAS databridge repo.

### ISSUE THREAD

**Issue by suman-v** [eclipse-basyx/basyx-databridge#311]
I am trying to use Databridge functionality to connect Docker container with local opcua server running in my system. I followed all steps mentioned in this repo but still not able to connect to opcua server. It is trying to pick my system IP but showing errors
Repo: https://github.com/eclipse-basyx/basyx-applications/tree/main/opc2aas @FrankSchnicke 
 Please help me here.  
Thank you in advance. 
![image](https://github.com/eclipse-basyx/basyx-applications/assets/43817111/ab666eec-d1e9-4bc2-ab88-a2c14a2fa8ca)
![image](https://github.com/eclipse-basyx/basyx-applications/assets/43817111/b8364dfd-f909-4abb-9a7f-2de85d2221ac)
@aaronzi

**Comment by aaronzi** [comment]
I will close this as there has been no reply for almost two months. If this issue is not resolved, please reopen it.
