### ISSUE TITLE
issues while running example kafka-jsonata-aas

### ISSUE THREAD

**Issue by manthan410** [eclipse-basyx/basyx-databridge#70]
Hi,
I was trying follow the example provide in the readme `An integration example between Kafka, Jsonata and AAS` . While the dummy kafka producer, aaserver work fine. But, I get an error after running for the databridge kafka-jsonata-aas example code as shown below:

`[main] WARN basyx.components.databridge.core.configuration.loader.FileConfigurationLoader - No exterior config file found in defined path. Trying to load config file from classpath...`

I believe the loader is not able to locate the config files present in the `src/main/resources`. Can you let me know how to fix this?

**Comment by FrankSchnicke** [comment]
This warning is just there to indicate that it is loading from the classpath. If it would not find the resources, an error message would be printed. Thus, the configuration is found and utilized correctly if you don't see an error message.
